### ISSUE TITLE
Selecting gloves skins and i get this one, any fix?

### ISSUE THREAD

**Issue by marianstefanel** [LielXD/CS2-WeaponPaints-Website#57]
![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/38572247/85106a4d-7eb6-46ee-bc22-7af5eb70a393)

**Comment by crashzk** [comment]
Probably some change you made may have caused this, I recommend sending the original files and testing.

**Comment by LielXD** [comment]
500 error is usually a server error saying the server is busy, it can be caused by serval reasons:
* ### php code is broken
for example infinite loops.

* ### the website host has poor performance
The host cpu or even ram cant handle the request so it throw this error.

*This can happen from other reasons but those are the main ones.*

it cant be the php code being broken because we can see on my and others websites its working good,
so if i can guess i think its your host performance.

**Comment by marianstefanel** [comment]
Thanks, i tested with the unmodified one and says the same error, so i guess it's the web host
